# Generated by Django 4.0.4 on 2022-06-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0003_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscriptores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
