# Generated by Django 4.0.4 on 2022-06-08 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0004_suscriptores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('terminado', models.BooleanField()),
                ('fecha_creacion', models.DateField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aplication.proyectos')),
            ],
        ),
    ]
