# Generated by Django 4.0.4 on 2022-06-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplication', '0005_proyectos_portafolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portafolio',
            name='imagen',
            field=models.ImageField(null=True, upload_to='portafolio'),
        ),
    ]
